import Config

config :logger, :default_formatter,
  metadata: [
    :attempt,
    :call_id,
    :class,
    :codex_status,
    :conflict_keys,
    :cwd,
    :dispatch_priority,
    :dispatch_source,
    :elapsed_ms,
    :error,
    :error_category,
    :exit_status,
    :gating_reason,
    :issue_id,
    :issue_identifier,
    :issue_priority,
    :issue_state,
    :last_event,
    :outcome_kind,
    :pending_request_count,
    :prepare_reason,
    :rate_limit_limit,
    :rate_limit_remaining,
    :rate_limit_reset,
    :recovered,
    :recovery_count,
    :reload_count,
    :reload_source,
    :retry_after,
    :session_id,
    :thread_id,
    :timeout_ms,
    :tool_name,
    :tracker_error,
    :turn_id,
    :watcher_error,
    :workflow_path,
    :workspace_error,
    :workspace_path
  ]
